use a2lfile::*;
use serde::Deserialize;
use std::fs;

// ==================== YAML Example Generator ====================

/// Generate a comprehensive YAML configuration example with all supported properties
pub(crate) fn generate_yaml_example() -> &'static str {
    r#"# =============================================================================
# A2L YAML Configuration Example
# Generated by: a2ltool --yaml-example
# Reference: A2L_YAML_CONFIG_SPEC.md
#
# This file demonstrates ALL supported YAML properties with representative values.
# Copy and modify as needed for your ECU project.
# =============================================================================

a2l_config:
  version: "1.71"

  # ---- Project Information ----
  project:
    name: "EngineControlProject"
    module_name: "EngineControlModule"

  # ---- Conversion Methods ----
  # A2L formula: PHYS = a * INT + b  (COEFFS_LINEAR a b)
  compu_methods:
    # LINEAR: identity mapping (PHYS = INT)
    - name: "LinearCompuMethod"
      type: "LINEAR"
      format: "%.3f"
      unit: ""
      coeffs_linear:
        a: 1.0   # scaling factor
        b: 0.0   # offset

    # TAB_VERB: string output table -> generates COMPU_VTAB
    - name: "StatusTable"
      type: "TAB_VERB"
      format: "%5.0"
      unit: ""
      value_pairs:
        - { in: 0.0, out: "OFF" }
        - { in: 1.0, out: "ON" }
        - { in: 2.0, out: "ERROR" }

    # TAB_NOINTP: numeric output table -> generates COMPU_TAB
    - name: "GearTable"
      type: "TAB_NOINTP"
      format: "%5.0"
      unit: ""
      value_pairs:
        - { in: 0.0, out: "0" }
        - { in: 1.0, out: "1" }
        - { in: 2.0, out: "2" }
        - { in: 3.0, out: "3" }

    # LINEAR: percentage mapping
    - name: "PercentCompuMethod"
      type: "LINEAR"
      format: "%5.1"
      unit: "%"
      coeffs_linear:
        a: 1.0
        b: 0.0

  # ---- Record Layouts ----
  record_layouts:
    # Scalar: single byte
    - name: "ScalarRecordLayout"
      fnc_values:
        position: 1
        datatype: "UBYTE"
        index_mode: "ROW_DIR"
        address_type: "PBYTE"

    # Word: two bytes
    - name: "WordRecordLayout"
      fnc_values:
        position: 1
        datatype: "UWORD"
        index_mode: "ROW_DIR"
        address_type: "PWORD"

    # Long: four bytes
    - name: "LongRecordLayout"
      fnc_values:
        position: 1
        datatype: "ULONG"
        index_mode: "ROW_DIR"
        address_type: "PLONG"

    # Signed byte: for signed parameters
    - name: "SignedRecordLayout"
      fnc_values:
        position: 1
        datatype: "SBYTE"
        index_mode: "ROW_DIR"
        address_type: "PBYTE"

  # ---- Measurements (ECU observables) ----
  measurements:
    # Basic UWORD measurement with all properties
    - name: "EngineSpeed"
      description: "Engine speed measurement"
      datatype: "UWORD"
      compu_method: "LinearCompuMethod"
      resolution: 0
      accuracy: 0.0
      lower_limit: 0.0
      upper_limit: 8000.0
      ecu_address: "0x1000"
      unit: "RPM"
      format: "%6.0"

    # UBYTE with percentage compu method
    - name: "ThrottlePosition"
      description: "Throttle position sensor"
      datatype: "UBYTE"
      compu_method: "PercentCompuMethod"
      lower_limit: 0.0
      upper_limit: 100.0
      ecu_address: "0x2000"
      unit: "%"
      format: "%5.1"

    # SBYTE measurement (signed, range -128..127)
    - name: "CoolantTemp"
      description: "Engine coolant temperature"
      datatype: "SBYTE"
      compu_method: "LinearCompuMethod"
      lower_limit: -40.0
      upper_limit: 120.0
      ecu_address: "0x3000"
      unit: "degC"
      format: "%6.1"

    # UBYTE with TAB_VERB + bit_mask + byte_order
    - name: "EngineStatus"
      description: "Engine status bitmask"
      datatype: "UBYTE"
      compu_method: "StatusTable"
      lower_limit: 0.0
      upper_limit: 2.0
      ecu_address: "0x4000"
      format: "%5.0"
      bit_mask: "0x03"
      byte_order: "MSB_LAST"

    # UWORD voltage measurement
    - name: "BatteryVoltage"
      description: "Battery voltage"
      datatype: "UWORD"
      compu_method: "LinearCompuMethod"
      lower_limit: 0.0
      upper_limit: 20000.0
      ecu_address: "0x5000"
      unit: "mV"
      format: "%7.0"

    # UWORD with TAB_NOINTP compu method
    - name: "CurrentGear"
      description: "Current gear position"
      datatype: "UBYTE"
      compu_method: "GearTable"
      lower_limit: 0.0
      upper_limit: 3.0
      ecu_address: "0x6000"
      format: "%5.0"

    # UBYTE percentage
    - name: "FuelLevel"
      description: "Fuel level"
      datatype: "UBYTE"
      compu_method: "PercentCompuMethod"
      lower_limit: 0.0
      upper_limit: 100.0
      ecu_address: "0x7000"
      unit: "%"
      format: "%5.1"

    # UWORD speed
    - name: "VehicleSpeed"
      description: "Vehicle speed"
      datatype: "UWORD"
      compu_method: "LinearCompuMethod"
      lower_limit: 0.0
      upper_limit: 300.0
      ecu_address: "0x8000"
      unit: "km/h"
      format: "%6.0"

  # ---- Characteristics (ECU calibratable parameters) ----
  characteristics:
    # VALUE type: basic UWORD scalar
    - name: "TargetIdleSpeed"
      description: "Target idle speed"
      type: "VALUE"
      datatype: "UWORD"
      ecu_address: "0x12345678"
      record_layout: "WordRecordLayout"
      compu_method: "LinearCompuMethod"
      lower_limit: 600.0
      upper_limit: 1200.0
      format: "%8.1"

    # VALUE type: UWORD with percentage
    - name: "FuelInjectionTime"
      description: "Fuel injection time"
      type: "VALUE"
      datatype: "UWORD"
      ecu_address: "0x12345680"
      record_layout: "WordRecordLayout"
      compu_method: "LinearCompuMethod"
      lower_limit: 1.0
      upper_limit: 50.0
      format: "%6.2"

    # VALUE type: SBYTE with signed record layout
    - name: "IgnitionAdvance"
      description: "Ignition timing advance"
      type: "VALUE"
      datatype: "SBYTE"
      ecu_address: "0x12345688"
      record_layout: "SignedRecordLayout"
      compu_method: "LinearCompuMethod"
      lower_limit: -10.0
      upper_limit: 50.0
      format: "%6.1"

    # VALUE type: UWORD lambda target
    - name: "LambdaTarget"
      description: "Target lambda value"
      type: "VALUE"
      datatype: "UWORD"
      ecu_address: "0x12345690"
      record_layout: "WordRecordLayout"
      compu_method: "LinearCompuMethod"
      lower_limit: 1.0
      upper_limit: 15.0
      format: "%5.3"

    # VALUE type: UWORD percentage
    - name: "EGR_Rate"
      description: "Exhaust gas recirculation rate"
      type: "VALUE"
      datatype: "UWORD"
      ecu_address: "0x12345698"
      record_layout: "WordRecordLayout"
      compu_method: "PercentCompuMethod"
      lower_limit: 0.0
      upper_limit: 100.0
      format: "%5.1"

    # VALUE type: ULONG long integer
    - name: "TurboBoostTarget"
      description: "Turbo boost pressure target"
      type: "VALUE"
      datatype: "ULONG"
      ecu_address: "0x123456A0"
      record_layout: "LongRecordLayout"
      compu_method: "LinearCompuMethod"
      lower_limit: 50.0
      upper_limit: 250.0
      format: "%6.1"

    # VALUE type: UWORD torque limit
    - name: "MaxTorqueLimit"
      description: "Maximum torque limit"
      type: "VALUE"
      datatype: "UWORD"
      ecu_address: "0x123456A8"
      record_layout: "WordRecordLayout"
      compu_method: "LinearCompuMethod"
      lower_limit: 0.0
      upper_limit: 500.0
      format: "%6.1"

  # ---- Groups (organizational structure) ----
  groups:
    # Independent root group with measurements
    - name: "EngineSpeedGroup"
      description: "Engine speed related measurements"
      root: true
      members:
        - { type: "MEASUREMENT", name: "EngineSpeed" }
        - { type: "MEASUREMENT", name: "ThrottlePosition" }
        - { type: "MEASUREMENT", name: "VehicleSpeed" }

    # Root group with single measurement
    - name: "TemperatureGroup"
      description: "Temperature related measurements"
      root: true
      members:
        - { type: "MEASUREMENT", name: "CoolantTemp" }

    # Root group with characteristics
    - name: "FuelControlGroup"
      description: "Fuel control parameters"
      root: true
      members:
        - { type: "CHARACTERISTIC", name: "FuelInjectionTime" }
        - { type: "CHARACTERISTIC", name: "LambdaTarget" }

    - name: "IgnitionControlGroup"
      description: "Ignition control parameters"
      root: true
      members:
        - { type: "CHARACTERISTIC", name: "IgnitionAdvance" }
        - { type: "CHARACTERISTIC", name: "TargetIdleSpeed" }

    # Group with sub_groups (hierarchical nesting)
    - name: "PerformanceGroup"
      description: "Performance parameters"
      root: true
      sub_groups:
        - "TorqueSubGroup"
      members:
        - { type: "CHARACTERISTIC", name: "MaxTorqueLimit" }
        - { type: "CHARACTERISTIC", name: "TurboBoostTarget" }
        - { type: "CHARACTERISTIC", name: "EGR_Rate" }

    # Sub-group referenced by PerformanceGroup (no root attribute)
    - name: "TorqueSubGroup"
      description: "Torque related parameters"
      members:
        - { type: "CHARACTERISTIC", name: "MaxTorqueLimit" }
"#
}

// ==================== YAML config structs ====================

#[derive(Debug, Deserialize)]
pub(crate) struct A2LYamlConfig {
    pub a2l_config: YamlConfigRoot,
}

#[derive(Debug, Deserialize)]
pub(crate) struct YamlConfigRoot {
    pub version: Option<String>,
    pub project: YamlProjectConfig,
    #[serde(default)]
    pub compu_methods: Vec<YamlCompuMethodConfig>,
    #[serde(default)]
    pub record_layouts: Vec<YamlRecordLayoutConfig>,
    #[serde(default)]
    pub measurements: Vec<YamlMeasurementConfig>,
    #[serde(default)]
    pub characteristics: Vec<YamlCharacteristicConfig>,
    #[serde(default)]
    pub groups: Vec<YamlGroupConfig>,
}

#[derive(Debug, Deserialize)]
pub(crate) struct YamlProjectConfig {
    pub name: String,
    #[allow(dead_code)]
    pub module_name: Option<String>,
}

#[derive(Debug, Deserialize)]
pub(crate) struct YamlCompuMethodConfig {
    pub name: String,
    #[serde(rename = "type")]
    pub compu_type: String,
    pub format: String,
    pub unit: Option<String>,
    pub coeffs_linear: Option<YamlCoeffsLinearConfig>,
    pub value_pairs: Option<Vec<YamlValuePairConfig>>,
}

#[derive(Debug, Deserialize)]
pub(crate) struct YamlCoeffsLinearConfig {
    pub a: f64,
    pub b: f64,
}

#[derive(Debug, Deserialize)]
pub(crate) struct YamlValuePairConfig {
    pub r#in: f64,
    pub out: String,
}

#[derive(Debug, Deserialize)]
pub(crate) struct YamlRecordLayoutConfig {
    pub name: String,
    pub fnc_values: Option<YamlFncValuesConfig>,
}

#[derive(Debug, Deserialize)]
pub(crate) struct YamlFncValuesConfig {
    pub position: u16,
    pub datatype: String,
    pub index_mode: String,
    pub address_type: String,
}

#[derive(Debug, Deserialize)]
pub(crate) struct YamlMeasurementConfig {
    pub name: String,
    pub description: Option<String>,
    pub datatype: String,
    pub compu_method: String,
    pub resolution: Option<u16>,
    pub accuracy: Option<f64>,
    pub lower_limit: f64,
    pub upper_limit: f64,
    pub ecu_address: String,
    pub unit: Option<String>,
    pub format: Option<String>,
    pub byte_order: Option<String>,
    pub bit_mask: Option<String>,
}

#[derive(Debug, Deserialize)]
pub(crate) struct YamlCharacteristicConfig {
    pub name: String,
    pub description: Option<String>,
    #[serde(rename = "type")]
    pub char_type: String,
    #[allow(dead_code)]
    pub datatype: String,
    pub ecu_address: String,
    pub record_layout: String,
    pub compu_method: String,
    pub lower_limit: f64,
    pub upper_limit: f64,
    pub format: Option<String>,
}

#[derive(Debug, Deserialize)]
pub(crate) struct YamlGroupConfig {
    pub name: String,
    pub description: Option<String>,
    #[serde(default)]
    pub root: Option<bool>,
    #[serde(default)]
    pub sub_groups: Option<Vec<String>>,
    pub members: Vec<YamlGroupMember>,
}

#[derive(Debug, Deserialize)]
pub(crate) struct YamlGroupMember {
    #[serde(rename = "type")]
    pub member_type: String,
    pub name: String,
}

// ==================== Public entry point ====================

/// Load a YAML config file and generate an A2L file from it
pub(crate) fn load_yaml_to_a2l(path: &str) -> Result<A2lFile, String> {
    let content = fs::read_to_string(path)
        .map_err(|e| format!("Failed to read YAML file '{path}': {e}"))?;

    let config: A2LYamlConfig = serde_yaml::from_str(&content)
        .map_err(|e| format!("YAML parse error: {e}"))?;

    let root = &config.a2l_config;
    let mut a2l_file = a2lfile::new();

    // Set project name
    a2l_file.project.name = root.project.name.clone();

    // Set ASAP2_VERSION if specified
    if let Some(version) = &root.version {
        if let Some((major, minor)) = parse_version(version) {
            a2l_file.asap2_version = Some(Asap2Version::new(major, minor));
        }
    }

    let module = &mut a2l_file.project.module[0];

    // Create RECORD_LAYOUTs
    for rl_config in &root.record_layouts {
        module.record_layout.push(create_record_layout(rl_config)?);
    }
    if root.record_layouts.is_empty() {
        let mut default_rl = RecordLayout::new("ScalarRecordLayout".to_string());
        default_rl.fnc_values = Some(FncValues::new(
            1,
            DataType::Ubyte,
            IndexMode::RowDir,
            AddrType::Pbyte,
        ));
        module.record_layout.push(default_rl);
    }

    // Create COMPU_METHODs and associated COMPU_TAB / COMPU_VTAB
    for cm_config in &root.compu_methods {
        module.compu_method.push(create_compu_method(cm_config)?);
        // Create COMPU_VTAB for TAB_VERB conversions
        if let Some(vtab) = create_compu_vtab(cm_config)? {
            module.compu_vtab.push(vtab);
        }
        // Create COMPU_TAB for TAB_NOINTP with numeric outputs
        if let Some(tab) = create_compu_tab(cm_config)? {
            module.compu_tab.push(tab);
        }
    }

    // Create MEASUREMENTs
    for m_config in &root.measurements {
        module.measurement.push(create_measurement(m_config)?);
    }

    // Create CHARACTERISTICs
    for c_config in &root.characteristics {
        module.characteristic.push(create_characteristic(c_config)?);
    }

    // Create GROUPs
    for g_config in &root.groups {
        module.group.push(create_group(g_config)?);
    }

    Ok(a2l_file)
}

// ==================== Element creation functions ====================

fn create_record_layout(config: &YamlRecordLayoutConfig) -> Result<RecordLayout, String> {
    let mut rl = RecordLayout::new(config.name.clone());
    if let Some(fnc) = &config.fnc_values {
        rl.fnc_values = Some(FncValues::new(
            fnc.position,
            parse_data_type(&fnc.datatype)?,
            parse_index_mode(&fnc.index_mode)?,
            parse_addr_type(&fnc.address_type)?,
        ));
    }
    Ok(rl)
}

fn create_compu_method(config: &YamlCompuMethodConfig) -> Result<CompuMethod, String> {
    let compu_type = parse_compu_type(&config.compu_type)?;

    let mut cm = CompuMethod::new(
        config.name.clone(),
        format!("{} conversion method", config.name),
        compu_type,
        config.format.clone(),
        config.unit.clone().unwrap_or_default(),
    );

    match compu_type {
        ConversionType::Linear => {
            if let Some(coeffs) = &config.coeffs_linear {
                cm.coeffs_linear = Some(CoeffsLinear::new(coeffs.a, coeffs.b));
            }
        }
        ConversionType::TabNointp | ConversionType::TabIntp => {
            // Reference the COMPU_TAB with the same name
            if config.value_pairs.is_some() {
                cm.compu_tab_ref = Some(CompuTabRef::new(config.name.clone()));
            }
        }
        ConversionType::TabVerb => {
            // Reference the COMPU_VTAB with the same name
            if config.value_pairs.is_some() {
                cm.compu_tab_ref = Some(CompuTabRef::new(config.name.clone()));
            }
        }
        _ => {}
    }

    Ok(cm)
}

/// Create a COMPU_TAB for numeric tab conversions (TAB_NOINTP/TAB_INTP)
fn create_compu_tab(config: &YamlCompuMethodConfig) -> Result<Option<CompuTab>, String> {
    let compu_type = parse_compu_type(&config.compu_type)?;
    if compu_type != ConversionType::TabNointp && compu_type != ConversionType::TabIntp {
        return Ok(None);
    }

    let pairs = match &config.value_pairs {
        Some(p) if !p.is_empty() => p,
        _ => return Ok(None),
    };

    let pair_count = pairs.len() as u16;
    let mut tab = CompuTab::new(
        config.name.clone(),
        format!("{} table", config.name),
        compu_type,
        pair_count,
    );

    for pair in pairs {
        let out_val: f64 = pair.out.parse().map_err(|_| {
            format!(
                "CompuTab '{}' entry has non-numeric output '{}'. Use TAB_VERB for string outputs.",
                config.name, pair.out
            )
        })?;
        tab.tab_entry.push(TabEntryStruct::new(pair.r#in, out_val));
    }

    Ok(Some(tab))
}

/// Create a COMPU_VTAB for verbal tab conversions (TAB_VERB)
fn create_compu_vtab(config: &YamlCompuMethodConfig) -> Result<Option<CompuVtab>, String> {
    let compu_type = parse_compu_type(&config.compu_type)?;
    if compu_type != ConversionType::TabVerb {
        return Ok(None);
    }

    let pairs = match &config.value_pairs {
        Some(p) if !p.is_empty() => p,
        _ => return Ok(None),
    };

    let pair_count = pairs.len() as u16;
    let mut vtab = CompuVtab::new(
        config.name.clone(),
        format!("{} verbal table", config.name),
        ConversionType::TabVerb,
        pair_count,
    );

    for pair in pairs {
        vtab.value_pairs
            .push(ValuePairsStruct::new(pair.r#in, pair.out.clone()));
    }

    Ok(Some(vtab))
}

fn create_measurement(config: &YamlMeasurementConfig) -> Result<Measurement, String> {
    let mut m = Measurement::new(
        config.name.clone(),
        config.description.clone().unwrap_or_default(),
        parse_data_type(&config.datatype)?,
        config.compu_method.clone(),
        config.resolution.unwrap_or(0),
        config.accuracy.unwrap_or(0.0),
        config.lower_limit,
        config.upper_limit,
    );

    m.ecu_address = Some(EcuAddress::new(parse_address(&config.ecu_address)?));

    if let Some(format) = &config.format {
        m.format = Some(Format::new(format.clone()));
    }
    if let Some(unit) = &config.unit {
        m.phys_unit = Some(PhysUnit::new(ensure_ascii_unit(unit)));
    }
    if let Some(byte_order) = &config.byte_order {
        m.byte_order = Some(ByteOrder::new(parse_byte_order(byte_order)?));
    }
    if let Some(bit_mask) = &config.bit_mask {
        m.bit_mask = Some(BitMask::new(parse_hex_or_decimal(bit_mask)?));
    }

    Ok(m)
}

fn create_characteristic(config: &YamlCharacteristicConfig) -> Result<Characteristic, String> {
    let char_type = parse_characteristic_type(&config.char_type)?;
    let ecu_address = parse_address(&config.ecu_address)?;

    let mut c = Characteristic::new(
        config.name.clone(),
        config.description.clone().unwrap_or_default(),
        char_type,
        ecu_address,
        config.record_layout.clone(),
        0.0,
        config.compu_method.clone(),
        config.lower_limit,
        config.upper_limit,
    );

    if let Some(format) = &config.format {
        c.format = Some(Format::new(format.clone()));
    }

    Ok(c)
}

fn create_group(config: &YamlGroupConfig) -> Result<Group, String> {
    let mut g = Group::new(
        config.name.clone(),
        config.description.clone().unwrap_or_default(),
    );

    // Set ROOT attribute
    if config.root.unwrap_or(false) {
        g.root = Some(Root::new());
    }

    // Set SUB_GROUP references
    if let Some(subs) = &config.sub_groups {
        if !subs.is_empty() {
            let mut sg = SubGroup::new();
            sg.identifier_list = subs.clone();
            g.sub_group = Some(sg);
        }
    }

    let mut char_refs = Vec::new();
    let mut meas_refs = Vec::new();

    for member in &config.members {
        match member.member_type.to_uppercase().as_str() {
            "CHARACTERISTIC" => char_refs.push(member.name.clone()),
            "MEASUREMENT" => meas_refs.push(member.name.clone()),
            other => {
                eprintln!("Warning: unsupported group member type '{other}', skipping");
            }
        }
    }

    if !char_refs.is_empty() {
        let mut rc = RefCharacteristic::new();
        rc.identifier_list = char_refs;
        g.ref_characteristic = Some(rc);
    }
    if !meas_refs.is_empty() {
        let mut rm = RefMeasurement::new();
        rm.identifier_list = meas_refs;
        g.ref_measurement = Some(rm);
    }

    Ok(g)
}

// ==================== Parse helpers ====================

fn parse_data_type(type_str: &str) -> Result<DataType, String> {
    match type_str.trim().to_uppercase().as_str() {
        "UBYTE" => Ok(DataType::Ubyte),
        "SBYTE" => Ok(DataType::Sbyte),
        "UWORD" => Ok(DataType::Uword),
        "SWORD" => Ok(DataType::Sword),
        "ULONG" => Ok(DataType::Ulong),
        "SLONG" => Ok(DataType::Slong),
        "A_UINT64" => Ok(DataType::AUint64),
        "A_INT64" => Ok(DataType::AInt64),
        "FLOAT32_IEEE" => Ok(DataType::Float32Ieee),
        "FLOAT64_IEEE" => Ok(DataType::Float64Ieee),
        _ => Err(format!("Unsupported data type: {type_str}")),
    }
}

fn parse_compu_type(type_str: &str) -> Result<ConversionType, String> {
    match type_str.trim().to_uppercase().as_str() {
        "IDENTICAL" => Ok(ConversionType::Identical),
        "LINEAR" => Ok(ConversionType::Linear),
        "TAB_NOINTP" => Ok(ConversionType::TabNointp),
        "TAB_INTP" => Ok(ConversionType::TabIntp),
        "TAB_VERB" => Ok(ConversionType::TabVerb),
        "FORM" => Ok(ConversionType::Form),
        "RAT_FUNC" => Ok(ConversionType::RatFunc),
        _ => Err(format!("Unsupported conversion type: {type_str}")),
    }
}

fn parse_address(addr_str: &str) -> Result<u32, String> {
    let addr_str = addr_str.trim();
    if let Some(hex) = addr_str.strip_prefix("0x").or_else(|| addr_str.strip_prefix("0X")) {
        u32::from_str_radix(hex, 16).map_err(|e| format!("Address parse error '{addr_str}': {e}"))
    } else {
        addr_str
            .parse::<u32>()
            .map_err(|e| format!("Address parse error '{addr_str}': {e}"))
    }
}

fn parse_index_mode(mode: &str) -> Result<IndexMode, String> {
    match mode.trim().to_uppercase().as_str() {
        "ROW_DIR" => Ok(IndexMode::RowDir),
        "COLUMN_DIR" => Ok(IndexMode::ColumnDir),
        _ => Err(format!("Unsupported index mode: {mode}")),
    }
}

fn parse_addr_type(addr_type: &str) -> Result<AddrType, String> {
    match addr_type.trim().to_uppercase().as_str() {
        "PBYTE" => Ok(AddrType::Pbyte),
        "PWORD" => Ok(AddrType::Pword),
        "PLONG" => Ok(AddrType::Plong),
        "PLONGLONG" => Ok(AddrType::Plonglong),
        _ => Err(format!("Unsupported address type: {addr_type}")),
    }
}

fn parse_byte_order(order: &str) -> Result<ByteOrderEnum, String> {
    match order.trim().to_uppercase().as_str() {
        "MSB_LAST" | "LITTLE_ENDIAN" => Ok(ByteOrderEnum::MsbLast),
        "MSB_FIRST" | "BIG_ENDIAN" => Ok(ByteOrderEnum::MsbFirst),
        _ => Err(format!("Unsupported byte order: {order}")),
    }
}

fn parse_characteristic_type(char_type: &str) -> Result<CharacteristicType, String> {
    match char_type.trim().to_uppercase().as_str() {
        "VALUE" => Ok(CharacteristicType::Value),
        "CURVE" => Ok(CharacteristicType::Curve),
        "MAP" => Ok(CharacteristicType::Map),
        "CUBOID" => Ok(CharacteristicType::Cuboid),
        "VAL_BLK" => Ok(CharacteristicType::ValBlk),
        "ASCII" => Ok(CharacteristicType::Ascii),
        _ => Err(format!("Unsupported characteristic type: {char_type}")),
    }
}

fn parse_hex_or_decimal(value: &str) -> Result<u64, String> {
    let value = value.trim();
    if let Some(hex) = value.strip_prefix("0x").or_else(|| value.strip_prefix("0X")) {
        u64::from_str_radix(hex, 16).map_err(|e| format!("Value parse error '{value}': {e}"))
    } else {
        value
            .parse::<u64>()
            .map_err(|e| format!("Value parse error '{value}': {e}"))
    }
}

fn parse_version(version: &str) -> Option<(u16, u16)> {
    let parts: Vec<&str> = version.split('.').collect();
    if parts.len() == 2 {
        let major = parts[0].parse::<u16>().ok()?;
        let minor = parts[1].parse::<u16>().ok()?;
        Some((major, minor))
    } else {
        None
    }
}

fn ensure_ascii_unit(unit: &str) -> String {
    match unit {
        "°C" | "°c" => "degC".to_string(),
        "°F" | "°f" => "degF".to_string(),
        "‰" => "permille".to_string(),
        "Ω" | "ω" => "Ohm".to_string(),
        "μ" => "u".to_string(),
        "²" => "2".to_string(),
        "³" => "3".to_string(),
        _ => {
            if unit.chars().any(|c| c > '\u{007F}') {
                eprintln!("Warning: unit '{unit}' contains non-ASCII characters");
            }
            unit.to_string()
        }
    }
}
